### ISSUE TITLE
Sand != Blue

### ISSUE THREAD

**Issue by RikerW** [newbiedoodle/DesertSurvival#9]
Sand turns blue after starting to water grind.  Attaching screenshot.

**Comment by RikerW** [comment]
<img width="58" alt="screen shot 2016-04-06 at 6 19 10 pm" src="https://cloud.githubusercontent.com/assets/16050725/14337585/309453d0-fc24-11e5-8fc2-8f70e64e8a9c.png">

**Comment by quartata** [comment]
That's not from water grinding, that's nighttime.

**Comment by RikerW** [comment]
If this is night, it needs work.  I can't even read it.

**Comment by RikerW** [comment]
@quartata ninja'ed.

**Comment by quartata** [comment]
What terminal are you using? All the letters are perfectly visible for me at night.

**Comment by RikerW** [comment]
@quartata  I use the solarized dark colorscheme, it seems to screw stuff up.

**Comment by quartata** [comment]
We don't have *too* much control over what the colors are; we're limited to ANSI color codes.

**Comment by newbiedoodle** [comment]
Yeah, the color needs to be redecided. I'm probably going to add two "renderings" for each tile; one for day and night

**Comment by RikerW** [comment]
@newbiedoodle  I can start on that.

**Comment by RikerW** [comment]
https://github.com/newbiedoodle/DesertSurvival/commit/76e20ff99f05d2a9073ed6d92eb22ebb5fae00fa
